export const ActionTypes = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS : "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    FETCH_CART_ITEMS:"FETCH_CART_ITEMS",
    UPDATE_QUANTITY:"UPDATE_QUANTITY",
    ADD_PRODUCT:"ADD_PRODUCT"
};